- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      dnf:
        update_cache: true
      tags:
      - node
      - zsh
  tasks:
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/npm-pkgs.yml
  - include: tasks/git-setup.yml