- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      dnf:
        update_cache: true
      tags:
      - node
      - zsh
  tasks:
  # - include: tasks/core-setups.yml
  - include: tasks/core-setups.yml
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/npm-pkgs.yml
  - include: tasks/git-setup.yml
  - include: tasks/neovim-setup.yml
