- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  dnf:
    name: ["pkg-config", "cmake",]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  become: true
  dnf:
    name: [ "lua5.1", "unzip", "libtool", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  dnf:
    name: [ "curl", "htop", "golang", "lsof", "ccache", "ninja-build", "python3-pip", "dconf-editor", "moreutils" ]
  tags:
    - install
    - core
